version: '3.8'

services:
  mariadb:
    image: mariadb:latest
    container_name: mariadb-container
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}  # Root password for the MariaDB
      MYSQL_DATABASE: ${MYSQL_DATABASE}            # Initial database to be created
      MYSQL_USER: ${MYSQL_USER}                    # Non-root user
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}            # Password for the non-root user
    ports:
      - "3306:3306"
    volumes:
      - mariadb_data:/var/lib/mysql  # Persist database data
      # - ./db_init:/docker-entrypoint-initdb.d  # Mount the db_init directory
    networks:
      - backend-network

networks:
  backend-network:
    driver: bridge

volumes:
  mariadb_data:
